temperatures_july_first <- c(30, 32, 31, 29, 28, 27, 26) 
temperatures_july_second <- c(28,27,29,26,25,24,23)
temperatures_june_thirty <- c(25, 26, 27, 28, 29, 30, 31)
temperatures <- c(temperatures_june_thirty, temperatures_july_first, temperatures_july_second)
cat("Las temperaturas de los ultimos 3 diasm son: ", temperatures[])
cat("La temperatura minima es: ", min(temperatures))
cat("La temperatura maxima es: ", max(temperatures))
cat("La temperatura promedio es: ", mean(temperatures))
cat("La temperatura mediana es: ", median(temperatures))
cat("La temperatura ordenadas de mayot a menor es: ", sort(temperatures, decreasing = TRUE))